# Generated by Django 3.2.2 on 2021-05-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
