# Generated by Django 3.2.2 on 2021-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='test',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
