# Generated by Django 3.2.2 on 2021-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_income_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='test',
        ),
        migrations.AddField(
            model_name='expense',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
