# Generated by Django 3.2.3 on 2021-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_expense_lonlat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='lonlat',
        ),
        migrations.AddField(
            model_name='expense',
            name='lat',
            field=models.FloatField(blank=True, default=51, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='lon',
            field=models.FloatField(blank=True, default=22, null=True),
        ),
    ]
