# Generated by Django 3.2.2 on 2021-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210517_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='test',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
