# Generated by Django 3.2.2 on 2021-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_expense_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='lat',
            field=models.FloatField(blank=True, default=51, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='lon',
            field=models.FloatField(blank=True, default=22, null=True),
        ),
    ]
