# Generated by Django 3.2.2 on 2021-05-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_expense_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='test',
        ),
    ]
