# Generated by Django 3.2.2 on 2021-05-25 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_auto_20210524_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
