# Generated by Django 3.2.2 on 2021-05-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_expense_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncategory',
            name='income_expense',
        ),
    ]
